### ISSUE TITLE
Authorization always fails

### ISSUE THREAD

**Issue by runepiper** [PassKitInc/PHP-SDK#2]
My test script always returns `Invalid token. Please make sure your token is valid.`. I also tried `ListCertificates()` as well as `ListCampaigns()` which both return the same error.

```php
require 'PHP-SDK-master/passkit-v2-sdk.php';

$passkit = new PassKit(
    'API_KEY',
    'API_SECRET'
);

var_dump($passkit->GenerateCSR());
```

**Comment by chiukit** [comment]
Make sure you are using v2 API key and secret. If you are using the key from https://create.passkit.com, it will not work.

**Comment by runepiper** [comment]
Ahh ok, this makes sense, but where can I get the credentials for the v2 API?

**Comment by chiukit** [comment]
You can use https://cherrypie.passkit.net to get a key. However, the data is not interchange. That means the data in your previous key cannot be transferred into v2. 

v1 and v2 are two different system and database. v2 is a very fast system. So, I recommend you to use v2 instead of v1.

**Comment by runepiper** [comment]
Alright, thank you!
